### ISSUE TITLE
Support of .js fixtures

### ISSUE THREAD

**Issue by sraone** [marko-js/fixture-snapshots#1]
### Description

Snapshot can't be created when the template is using `await` or `{dyamic}` body content. Using Javascript fixtures would solve this issue.

### Why

```marko
//index.marko
<div>
  <await(input.model)>
	<@then|model|>
	  ${model}
	</@then>
  </await>
</div>
```

```javascript
//fixtures/data.js
module.exports = {
  model: Promise.resolve('hello');
}
```

### Is this something you're interested in working on?

Yes

**Comment by mlrawlings** [comment]
published in `1.1.0`
